In [1]:
import numpy as np

In [2]:
a=10,20,30
b={10,20,30}
print(type(a))
print(type(b))

<class 'tuple'>
<class 'set'>


In [3]:
a=np.array(a)
type(a)

numpy.ndarray

In [4]:
b=np.array([[1,2,3,4],[1,2,3,4]])
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [5]:
np.ndim(b)

2

In [6]:
c=np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])
c

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [7]:
np.ndim(c)

3

In [8]:
np.shape(b)

(2, 4)

In [9]:
np.shape(c)

(2, 2, 4)

In [10]:
np.shape(a)

(3,)

In [11]:
np.size(c)

16

In [12]:
from PIL import Image

In [13]:
img = Image.open(r"C:\Users\gavas\Downloads\download (3).jpeg")

#img.show()

In [14]:
image=np.array(img)

image

array([[[181,   1,   0],
        [181,   1,   0],
        [181,   1,   0],
        ...,
        [ 89,   8,   4],
        [ 79,   4,   0],
        [220, 147, 141]],

       [[181,   1,   0],
        [181,   1,   0],
        [181,   1,   0],
        ...,
        [ 89,   8,   4],
        [ 79,   4,   0],
        [220, 147, 141]],

       [[181,   1,   0],
        [181,   1,   0],
        [183,   1,   0],
        ...,
        [ 89,   8,   4],
        [ 79,   4,   0],
        [220, 147, 141]],

       ...,

       [[197,   2,   0],
        [197,   2,   0],
        [197,   2,   0],
        ...,
        [111,   8,   9],
        [ 98,   2,   3],
        [234, 143, 142]],

       [[197,   2,   0],
        [196,   1,   0],
        [197,   0,   0],
        ...,
        [113,   9,   8],
        [101,   3,   2],
        [238, 144, 142]],

       [[197,   2,   0],
        [196,   1,   0],
        [197,   0,   0],
        ...,
        [113,   9,   8],
        [101,   3,   2],
        [238, 144, 142]]

In [15]:
d=np.arange(1,51)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [16]:
d1=d.astype("float64")

In [17]:
d1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [18]:
d=d.reshape(5,10)
d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [19]:
d[::2,::2]

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49]])

In [20]:
d[0::,0::2]

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [21]:
#Vectorisation
def fun(l):
    return l*5

l=[1,2,3,4,5]
print(list(map(fun,l)))

[5, 10, 15, 20, 25]


In [22]:
l1=np.array(l)
l1*5

array([ 5, 10, 15, 20, 25])

In [23]:
a=[1,2,3,4,5]
b=[[2],[4],[6]]
print(a)
print(b)

[1, 2, 3, 4, 5]
[[2], [4], [6]]


In [24]:
a=np.array(a)
b=np.array(b)
c=a+b
c

array([[ 3,  4,  5,  6,  7],
       [ 5,  6,  7,  8,  9],
       [ 7,  8,  9, 10, 11]])

In [26]:
c

array([[ 3,  4,  5,  6,  7],
       [ 5,  6,  7,  8,  9],
       [ 7,  8,  9, 10, 11]])

In [27]:
np.sum(c)

np.int64(105)

In [28]:
np.min(c)

np.int64(3)

In [29]:
np.max(c)

np.int64(11)

In [33]:
np.argmax(a) #index Position

np.int64(4)